#!/bin/bash

counter=1
fileName=$HOME/kode/bibtexDatabase/references.bib
#fileName=$HOME/Dropbox/Apps/Overleaf/bibtexDatabase/references.bib
sed -i 's/\(^ *month\) *= *["{]{*jan}*[}"]/\1\ \ \ \ \ = {1}/i' $fileName
sed -i 's/\(^ *month\) *= *["{]{*feb}*[}"]/\1\ \ \ \ \ = {2}/i' $fileName
sed -i 's/\(^ *month\) *= *["{]{*mar}*[}"]/\1\ \ \ \ \ = {3}/i' $fileName
sed -i 's/\(^ *month\) *= *["{]{*apr}*[}"]/\1\ \ \ \ \ = {4}/i' $fileName
sed -i 's/\(^ *month\) *= *["{]{*may}*[}"]/\1\ \ \ \ \ = {5}/i' $fileName
sed -i 's/\(^ *month\) *= *["{]{*jun}*[}"]/\1\ \ \ \ \ = {6}/i' $fileName
sed -i 's/\(^ *month\) *= *["{]{*jul}*[}"]/\1\ \ \ \ \ = {7}/i' $fileName
sed -i 's/\(^ *month\) *= *["{]{*aug}*[}"]/\1\ \ \ \ \ = {8}/i' $fileName
sed -i 's/\(^ *month\) *= *["{]{*sep}*[}"]/\1\ \ \ \ \ = {9}/i' $fileName
sed -i 's/\(^ *month\) *= *["{]{*oct}*[}"]/\1\ \ \ \ \ = {10}/i' $fileName
sed -i 's/\(^ *month\) *= *["{]{*nov}*[}"]/\1\ \ \ \ \ = {11}/i' $fileName
sed -i 's/\(^ *month\) *= *["{]{*dec}*[}"]/\1\ \ \ \ \ = {12}/i' $fileName
