#!/bin/bash
startdate=$1
enddate=$2
dt=$3
GFS_RES=$4
date=$startdate
temp="${enddate:0:10} ${enddate:11}"
epochend=$(date -d"$temp" +%s)
while true
do
	temp="${date:0:10} ${date:11}"
	epoch=$(date -d"$temp" +%s)
	if (( epoch <= epochend ))
	then
  	dates="$dates $date"
	else
		break
	fi
  date="$(date -u +'%Y-%m-%d_%T' --date="$temp UTC + $dt seconds")"
done

startdate=$(echo $startdate | sed 's/-//g' | sed 's/_//g' | sed 's/://g')
startdate="${startdate:0:8}/${startdate:8:2}"
t=0
for date in $dates
do
	ftime=`printf "%03d\n" "${t}"`
	temp="GFS_${GFS_RES}_${startdate:0:8}${startdate:9:2}_${ftime}h"
	if [[ ! -f "$temp" ]]
	then
		echo "Downloading NCEP data file $temp"
		curl --retry 360 --retry-delay 60 --retry-max-time 21600 --retry-connrefused -s --disable-epsv \
			   --connect-timeout 1000 -m 1000 -u anonymous:JonVegard.Venas@sintef.no \
			   -o $temp ftp://ftpprd.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.${startdate:0:11}/gfs.t${startdate:9:2}z.pgrb2.${GFS_RES}.f$ftime
	fi
	t=$(($t + $dt/3600))
done
