#!/bin/bash
# Several convenient linux commands
#
# Install dropbox using the following guide: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md
sudo add-apt-repository ppa:yann1ck/onedrive
sudo apt-get update
sudo apt install onedrive

## Initialize Onedrive to start on startup:
systemctl --user enable onedrive
systemctl --user start onedrive

~/.config/onedrive/refresh_token
# To see the logs run:
journalctl --user-unit=onedrive -f

## Run lsyncd
# Set up lsyncd here: https://www.howtoforge.com/how-to-synchronize-directories-using-lsyncd-on-ubuntu/
sudo cp ~/OneDrive/config/lsyncd.conf.lua /etc/lsyncd/lsyncd.conf.lua
systemctl start lsyncd
systemctl enable lsyncd
# Check status:
systemctl status lsyncd

# Start dropbox:
~/.dropbox-dist/dropboxd

# Build paraview
export MESA_INSTALL_PREFIX=/usr
cmake  ../paraview                                             \
  -GNinja                                                      \
  -DPARAVIEW_USE_PYTHON=ON                                     \
  -DPARAVIEW_USE_MPI=ON                                        \
  -DVTK_SMP_IMPLEMENTATION_TYPE=TBB                            \
  -DCMAKE_BUILD_TYPE=Release                                   \
  -DPARAVIEW_BUILD_QT_GUI=OFF                                  \
  -DVTK_USE_X=OFF                                              \
  -DOPENGL_INCLUDE_DIR=IGNORE                                  \
  -DOPENGL_xmesa_INCLUDE_DIR=IGNORE                            \
  -DOPENGL_gl_LIBRARY=IGNORE                                   \
  -DOSMESA_INCLUDE_DIR=${MESA_INSTALL_PREFIX}/include          \
  -DOSMESA_LIBRARY=/usr/lib/x86_64-linux-gnu/libOSMesa.so      \
  -DVTK_OPENGL_HAS_OSMESA=ON                                   \
  -DVTK_USE_OFFSCREEN=OFF                                      \
  -DPYTHON_EXECUTABLE=/usr/bin/python3

ninja

## Unmute spotify
pavucontrol

