#!/bin/bash
export WRF_DIR=$HOME/kode/WRF
export TEST_DIR=$WRF_DIR/TESTS
export DIR=$WRF_DIR/Build_WRF/LIBRARIES
export CC=gcc
export CXX=g++
export FC=gfortran
export FCFLAGS=-m64
export F77=gfortran
export FFLAGS=-m64
export JASPERLIB=$DIR/grib2/lib
export JASPERINC=$DIR/grib2/include

export PATH=$DIR/netcdf/bin:$PATH
export NETCDF=$DIR/netcdf

export PATH=$DIR/mpich/bin:$PATH

export LDFLAGS=-L$DIR/grib2/lib
export CPPFLAGS=-I$DIR/grib2/include
