#!/bin/bash
export WPSDATADIRECTORY=$HOME/WPS_DATA
export WRFDIRECTORY=$HOME/kode/WRF
export TEST_DIR=$WRFDIRECTORY/TESTS
export DIR=$WRFDIRECTORY/Build_WRF/LIBRARIES
export CC=gcc
export CXX=g++
export FC=gfortran
export FCFLAGS=-m64
export F77=gfortran
export FFLAGS=-m64
export JASPERLIB=$DIR/grib2/lib
export JASPERINC=$DIR/grib2/include
export JASPER_INC=$DIR/grib2/include
export PNG_INC=$DIR/grib2/include

export PATH=$DIR/netcdf/bin:$PATH
export NETCDF=$DIR/netcdf
export NCEPLIBS_DIR=$DIR/nceplibs

export PATH=$DIR/mpich/bin:$PATH

export LDFLAGS=-L$DIR/grib2/lib
export CPPFLAGS=-I$DIR/grib2/include

export NETCDF_classic=1
export LD_LIBRARY_PATH=$WRFDIRECTORY/Build_WRF/LIBRARIES/grib2/lib:$LD_LIBRARY_PATH
export NCARG_COLORMAPS=$HOME/kode/colormaps:$NCARG_ROOT/lib/ncarg/colormaps

# Install Miniconda
# wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
# conda create -n ncl_stable -c conda-forge ncl
# conda config --set changeps1 False # to remove (base) in fron of prompt
# conda update -n ncl_stable -c conda-forge --all
# source activate ncl_stable
# conda activate ncl_stable

