#!/bin/bash
export WPSDATADIRECTORY=$HOME/WPS_DATA
export WRFDIRECTORY=$HOME/kode/WRF
export TEST_DIR=$WRFDIRECTORY/TESTS
export DIR=$WRFDIRECTORY/Build_WRF/LIBRARIES
export CC=gcc
export CXX=g++
export FC=gfortran
export FCFLAGS=-m64
export F77=gfortran
export FFLAGS=-m64
export JASPERLIB=$DIR/grib2/lib
export JASPERINC=$DIR/grib2/include

export PATH=$DIR/netcdf/bin:$PATH
export NETCDF=$DIR/netcdf

export PATH=$DIR/mpich/bin:$PATH

export LDFLAGS=-L$DIR/grib2/lib
export CPPFLAGS=-I$DIR/grib2/include

export NETCDF_classic=1
export LD_LIBRARY_PATH=$WRFDIRECTORY/Build_WRF/LIBRARIES/grib2/lib:$LD_LIBRARY_PATH
export NCARG_COLORMAPS=$HOME/kode/colormaps:$NCARG_ROOT/lib/ncarg/colormaps
source activate ncl_stable
